import { cn } from '@/lib/utils'
import './styles/globals.css'
import { Inter } from 'next/font/google'
import { Navbar } from '@/components/navbar'
import { Toaster } from '@/components/ui/toaster'
import { QueryProvider } from '@/components/providers/query-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    authModal
}: {
    children: React.ReactNode
    authModal: React.ReactNode
}) {
    return (
        <html lang="en" className={cn(
            'bg-white text-slate-900 antialiased light',
            inter.className
        )}>
            <body className='min-h-screen bg-slate-50 pt-12 antialiased'>

                <QueryProvider>

                    {/* @ts-expect-error server component */}
                    <Navbar />

                    {authModal}

                    <div className='container max-w-7xl mx-auto h-full pt-12'>
                        {children}
                    </div>

                    <Toaster />
                </QueryProvider>
            </body>
        </html>
    )
}
